<?php
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


function FibonacciSequence($maxValue) {

	$first = 1;
	$second = 2;

	$sequence = array();
	$sequence[] = $first;
	$sequence[] = $second;

	do {
		$next = $first + $second;
		$sequence[] = $next;

		$first = $second;
		$second = $next;
	} while (($first + $second) < $maxValue);

	return $sequence;
}

$arr = FibonacciSequence(4000000);

foreach ($arr as $ar) {
	if ($ar % 2 == 0) {
		$sum += $ar;
		//echo $ar . '<br />';
	}
	
}

echo $sum;

?>